Router.addRoutes [{
  route: 'home'
  path: '/'
  controller: "ExampleController"
  page:
    title: "jquery-select2"
    subtitle: "A Blaze UI select2 component that supports reactive search."
},{
  route: "officialDocs"
  path: "http://ivaynberg.github.io/select2/"
  external: true
  page:
    title: "Official Docs"
    subtitle: "Select2 Pro"
  nav:
    priority: 999
    icon: "icon-book"
},{
  route: 'gitHub'
  path: "https://github.com/LumaPictures/meteor-jquery-select2"
  external: true
  page:
    title: "GitHub"
    subtitle: "Open Source Repo"
  nav:
    priority: 1000
    icon: 'icon-github'
},{
  route: 'reportBugs'
  path: "https://github.com/LumaPictures/meteor-jquery-select2/issues/new"
  external: true
  page:
    title: "Report Bugs"
    subtitle: "GitHub Issues"
},{
  route: 'source'
  path: "http://LumaPictures.github.io/meteor-jquery-select2/"
  external: true
  page:
    title: "Annotated Source"
    subtitle: "GitHub pages generated by Groc"
  nav:
    priority: 1001
    icon: 'icon-code'
},{
  route: 'build'
  path: "https://travis-ci.org/LumaPictures/meteor-jquery-select2"
  external: true
  page:
    title: "Build Status"
    subtitle: "Continuous Integration by Travis CI"
  nav:
    priority: 1002
    icon: 'icon-cogs'
}]

Router.initialize()
